MONGO_ADMINUSERNAME = "root"
MONGODB_ADMINPASSWORD = "example"
MONGO_SERVER = "localhost"
MONGO_URL = mongodb://$MONGO_ADMINUSERNAME/$MONGODB_ADMINPASSWORD@$MONGO_SERVER:27017/
APP_SERVER = "localhost"
APP_PORT = "8080"
ENV_NAME = "default"
